# Generated by Django 5.2.7 on 2025-11-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
